cadastro/base/urls.py
from django.urls import path

from cadastro.base import views

app_name = 'base'
urlpatterns = [
    path('cadastrar_pessoa/', views.cadastrar_pessoa, name='cadastrar_pessoa'),
    path('listar_pessoa/', views.listar_pessoa, name='listar_pessoa'),
]

cadastro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastro.base.urls')),
]

cadastro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from ordered_model.models import OrderedModel


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Pessoa(OrderedModel):
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    idade = models.IntegerField(default=0)
    data_de_nascimento = models.DateField()
    email = models.EmailField()
    apelido = models.CharField(max_length=100, blank=True)
    obs = models.TextField(max_length=400, blank=True)

    class Meta(OrderedModel.Meta):
        verbose_name_plural = 'pessoas'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

cadastro/base/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms

from cadastro.base.models import Pessoa


class CadastroForm(forms.ModelForm):
    nome = forms.CharField(max_length=100)
    sobrenome = forms.CharField(max_length=100)
    idade = forms.IntegerField(min_value=0, widget=forms.NumberInput)
    data_de_nascimento = forms.DateField(
        widget=DatePickerInput(format='%d/%m/%Y'))
    email = forms.EmailField()
    apelido = forms.CharField(max_length=100, required=False)
    obs = forms.CharField(widget=forms.Textarea, max_length=400, required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Pessoa
        fields = ('nome', 'sobrenome', 'idade', 'data_de_nascimento', 'email', 'apelido', 'obs')

cadastro/base/views.py
from django.shortcuts import render

from cadastro.base import facade
from cadastro.base.forms import CadastroForm


def listar_pessoa(request):
    pessoas = facade.listar_pessoas_ordenado()
    return render(request, 'sistema/listar_pessoa.html', context={'pessoas': pessoas})


def cadastrar_pessoa(request):
    initial_dict = facade.get_random_name()
    form = CadastroForm(initial=initial_dict)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CadastroForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return listar_pessoa(request)

        else:
            print(form.errors)

    return render(request, 'sistema/cadastrar_pessoa.html', {'form': form})

cadastro/base/templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>

    <title> Sistema - {% block title_block %}{% endblock %}</title>
</head>
<body>
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'base:cadastrar_pessoa' %}">Empresa X</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'base:cadastrar_pessoa' %}">Cadastrar <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'base:listar_pessoa' %}">Lista <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/admin/base/pessoa/">Editar cadastro <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<div>
    {% block body_block %}
    this is body block default content.
    {% endblock %}
</div>
{% block body_end_block %}
{% endblock %}
</body>
</html>

cadastro/base/templates/base/cadastro.html
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <title>Cadastro de pessoas</title>
</head>
<body>

<h1>Cadastre-se:</h1>
<div>
    <form id="cadastro_form" method="post" action="/cadastro_pessoa/">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="submit" value="Criar Pessoa"/>
    </form>
</div>

</body>
</html>

cadastro/base/templates/sistema/cadastrar_pessoa.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}


{% block title_block %} Cadastro de pessoas {% endblock %}


{% block body_block %}
{{ form.media }}            {# Adds date-picker required JS and CSS #}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">Cadastro de Pessoas</h1>
            <hr class="mt-0 mb-4">
            <form id="cadastro_form" method="POST" action="/cadastrar_pessoa/">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" name="submit" value="Criar Pessoa"/>
            </form>
        </div>
    </div>
</div>
</form>
</div>

{% endblock %}


</html>

cadastro/base/templates/sistema/listar_pessoa.html
{% extends 'base/base.html' %}

{% block title_block %} Lista {% endblock %}

{% block body_block %}

{% if pessoas %}
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Sobrenome</th>
        <th scope="col">E-mail</th>
    </tr>
    </thead>
    <tbody>
    {% for pessoa in pessoas %}

    <tr>
        <th scope="row">1</th>
        <td>{{ pessoa.nome }}</td>
        <td>{{ pessoa.sobrenome }}</td>
        <td>{{ pessoa.email }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h1> Nenhuma pessoa cadastrada.</h1>
{% endif %}
{% endblock %}